### ISSUE TITLE
can u consider this new ctf from owasp mstf crackme level 4

### ISSUE THREAD

**Issue by balook** [nibarius/learning-frida#14]
https://github.com/OWASP/owasp-mstg/tree/master/Crackmes/Android/Level_04

**Comment by nibarius** [comment]
Thanks for the suggestion, I'll see if I can take a look at this at some point.

Note to self: There is more details about this at https://github.com/OWASP/owasp-mstg/tree/master/Crackmes#uncrackable-mobile-apps

**Comment by balook** [comment]
Tq

**Comment by nibarius** [comment]
I've taken a look at this now, and almost all it's focus is on reverse engineering native code which I'm not that skilled at. This is something that way beyond my skill level so I won't be able to solve this one.
